# Use postgres/example user/password credentials
version: '3.1'

networks:
  db_net:
    driver: bridge

volumes:
    mysql_db: {}

services:

  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql_db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=test_db
    networks:
      - db_net
    ports:
      - 3306:3306
      
   adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - db_net
    ports:
      - 8080:8080
