apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  # values are base64 encoded, which obscures them but does NOT provide
  # any useful level of confidentiality
  tls.crt: |
    MIIDCTCCAfGgAwIBAgIUbDnsvXOJRvEpfTaG0qrTpf2rqgEwDQYJKoZIhvcNAQEL
    BQAwFDESMBAGA1UEAwwJbG9jYWwuY29tMB4XDTI0MDEwODEyMjcyN1oXDTI1MDEw
    NzEyMjcyN1owFDESMBAGA1UEAwwJbG9jYWwuY29tMIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEAsdyji1VVO6tkfQi6IphrTrNJG1qUm7jI5rdq8qCEhApC
    W5T8AyBvqq8Ap0bvn9L2NnI5CQsLPlMb953yY5Kyl0yYQZL8R8WGsAwL7sT/5Xpi
    iADj9EzBZEHt3TrFW8vUyZmr4SI1hcB5hdSt00ycEVB1yn6DZUQXOpyIovC1TePL
    7zsV782MK5HvzcmfA1eHaRBrn31oPLiApUEigTKtn1ZH4V1YhJmqP+VvzKmSLPO+
    byA8C2ecsdGCiATIT2MDme5psCzE0JmkbVNMfBy+zfHxsM1TrlBq0oIQFQS4ssGE
    Kyvn2kgGQX7hAH3LQLpCYbQu0XA/U41o8dTrEbJwYwIDAQABo1MwUTAdBgNVHQ4E
    FgQULsnSFspQL9xAI+WnmuH6sOS/wzYwHwYDVR0jBBgwFoAULsnSFspQL9xAI+Wn
    muH6sOS/wzYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEADuUq
    ohu6Dcd93qoGyVEf5svzFuwSNPxH6H+6kBlHZddqc0yxqN3TSKDy+MU8MDi8VGGb
    m3qvqRHKdjkTQuOhkihr8Zv2yayinj08w14lLdw4J0Am79z70rea6GMGqzk33dyL
    IzlP5q4Vhxyp5aFej2G8kN/eYzZx7x3v46MmB0qOxpGbTEbfOxxh4HPMCvlDmOns
    6AogUvrDHFCLc54ahbODtzUcr4kzjph4v++yXe2xUuQt2nqasyQIL2hrGj06SYnc
    OivdrgvMNXN/wIpIOxpT0kryRRFK9fHRPAT5kNcdDn9z0kAzE5txn+k2ER+uP6dT
    jT9TNscNcamhZwrEfQ== 
  # In this example, the key data is not a real PEM-encoded private key
  tls.key: |
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCx3KOLVVU7q2R9
    CLoimGtOs0kbWpSbuMjmt2ryoISECkJblPwDIG+qrwCnRu+f0vY2cjkJCws+Uxv3
    nfJjkrKXTJhBkvxHxYawDAvuxP/lemKIAOP0TMFkQe3dOsVby9TJmavhIjWFwHmF
    1K3TTJwRUHXKfoNlRBc6nIii8LVN48vvOxXvzYwrke/NyZ8DV4dpEGuffWg8uICl
    QSKBMq2fVkfhXViEmao/5W/MqZIs875vIDwLZ5yx0YKIBMhPYwOZ7mmwLMTQmaRt
    U0x8HL7N8fGwzVOuUGrSghAVBLiywYQrK+faSAZBfuEAfctAukJhtC7RcD9TjWjx
    1OsRsnBjAgMBAAECggEANxhevNGBJouwBB9I8WB/lRBqbAPCFv7FlNpqUaAxjGlV
    JuNesWVB0gCF1ktd/QcvZ6w4SLnYEMVT239cz0Vo9v8uBtoONflVAIGqzJrPnfks
    Pm7wLgP8wB7AHRCQhB/+2Tg2CvY62CTIQBGiitqnWaGv6zsHXr4Z5/kHRloD/401
    sgEvf9sHGId0Ze2XGt1riri6ai5rQeoNXuGipBvL8qj+to1VCDQeVf05RDnW1T12
    K++vT/DpThItKWz2IoXr7Q09QuK5GKPci7kqIiCmE/Zx3kETRvz3oILffFCT1vvS
    K5VTTSc18dZqHuO1bWNin+v/af0xw6Xr4ldhShuQEQKBgQDW/OA/Z+k0J4Zqx1KA
    wqts878Ks9zD9tshFZ8GeBlDY9ATWyIrISo4Rzcm27dvCyxDCl0+BlUenAhJhz0N
    j5Q/ywYdb8sgqxM1ed/FjfIbJuA6GaV2nP2RUuuEji6x2s6KF5G9Nuz3j7M5vZ12
    gpYxkUM02zDFE4JwGpUTSPFUCQKBgQDTyq9Bzi/xUuPF7NqmcyguyL5hLHvj1jj7
    oD2mYq0+azq6c1cqJA3y5ZtqtKeyyVpI8p2meMff8MtQIpyiIMRUn9GbroGyVBhe
    fL4K6vQl3uAcVlcE4Jg8YbVJ7Q28maI7URVYN88vA449/MDGuaqng9oD6VpHARWB
    6RoknLI0CwKBgQDAFKteuz52pKHKIVArTsLO03Bq5YxnYdUi2Ch/JSqdNT6hLJl4
    o2cPZUF3bHOVuQvQ0h/A3POMJ6iX2UbJKPExlfler5VzGKZO7xbpcQtRCwjnoCZf
    taAwCT/37Pj3WyGR68EAp2RNQ4zEGA/p5H7AxqKfRP9r9SRjeLycwF0t0QKBgH/h
    Cu8t4w7QYM16VQ9ZyvJsrV8ZL/kCuUddmrvjKv3cWwqHaCL+wBlgf/Xu/K7cGxKe
    w4fnt6/Ewc4yB+dw53q9QR/CP3eAhXJP2aPX9/EB4MnbbBF61xDmYkMvyjKNhUJR
    lBS/Je8aM4HEIlYbdypMV5AzDxp+UhEtwWZH4uW/AoGAAtCMNU62dR+JnZ7ckId4
    S98AkLR84hRXOqAqwgTrZzkJe8IQMkFN+tsPZYRaviiN2pEqyZa7IytA2wFXxXd+
    dR3mh+7ZaFHcqAERPuSKqCcjIfjFSjBO+/MiYCPbGEv15JaX6OLWYHy/ciXBxcZH
    HdLShsPTZ80Med3utuSw4IM=

# генерация ключа
	
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=foo.bar.com"
