apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deploy
  namespace: default
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi